Update action.yml

diff --git a/actions/create-confluence-page/action.yml b/actions/create-confluence-page/action.yml
--- a/actions/create-confluence-page/action.yml
+++ b/actions/create-confluence-page/action.yml
@@ -53,34 +53,34 @@ runs:
             })
           ).data[0];
 
-    - name: Extract JIRA Issue Key from PR Description
-      id: extract-jira-key
-      run: |
-        jira_issue_key=$(echo "${{ fromJson(steps.get_pr_data.outputs.result).body }}" | grep -oE '[A-Z]+-[0-9]+' | head -n 1)
-        if [ -z "$jira_issue_key" ]; then
-          echo "No JIRA issue key found in the PR description."
-          exit 1
-        fi
-        sanitized_jira_issue_key=$(echo "$jira_issue_key" | sed 's/[^a-zA-Z0-9_-]//g')
-        echo "jira_issue_key=$sanitized_jira_issue_key" >> $GITHUB_ENV
-      shell: bash
+    # - name: Extract JIRA Issue Key from PR Description
+    #   id: extract-jira-key
+    #   run: |
+    #     jira_issue_key=$(echo "${{ fromJson(steps.get_pr_data.outputs.result).body }}" | grep -oE '[A-Z]+-[0-9]+' | head -n 1)
+    #     if [ -z "$jira_issue_key" ]; then
+    #       echo "No JIRA issue key found in the PR description."
+    #       exit 1
+    #     fi
+    #     sanitized_jira_issue_key=$(echo "$jira_issue_key" | sed 's/[^a-zA-Z0-9_-]//g')
+    #     echo "jira_issue_key=$sanitized_jira_issue_key" >> $GITHUB_ENV
+    #   shell: bash
 
-    - name: Fetch JIRA Issue Details
-      id: fetch-jira-details
-      run: |
-        response=$(curl -u ${{ inputs.confluence-email }}:${{ inputs.confluence-api-token }} \
-          -X GET -H "Content-Type: application/json" \
-          "${{ inputs.confluence-url }}/rest/api/2/issue/${{ env.jira_issue_key }}")
+    # - name: Fetch JIRA Issue Details
+    #   id: fetch-jira-details
+    #   run: |
+    #     response=$(curl -u ${{ inputs.confluence-email }}:${{ inputs.confluence-api-token }} \
+    #       -X GET -H "Content-Type: application/json" \
+    #       "${{ inputs.confluence-url }}/rest/api/2/issue/${{ env.jira_issue_key }}")
         
-        jira_summary=$(echo $response | jq -r '.fields.summary')
-        jira_description=$(echo $response | jq -r '.fields.description')
-        if [ -z "$jira_summary" ]; then
-          echo "Failed to fetch JIRA issue details."
-          exit 1
-        fi
-        echo "jira_summary=$jira_summary" >> $GITHUB_ENV
-        echo "jira_description=$jira_description" >> $GITHUB_ENV
-      shell: bash
+    #     jira_summary=$(echo $response | jq -r '.fields.summary')
+    #     jira_description=$(echo $response | jq -r '.fields.description')
+    #     if [ -z "$jira_summary" ]; then
+    #       echo "Failed to fetch JIRA issue details."
+    #       exit 1
+    #     fi
+    #     echo "jira_summary=$jira_summary" >> $GITHUB_ENV
+    #     echo "jira_description=$jira_description" >> $GITHUB_ENV
+    #   shell: bash
 
     - name: Get Release
       id: get-release
@@ -111,11 +111,11 @@ runs:
         RELEASE_URL: ${{ fromJson(steps.get-release.outputs.result).url }}
         PR_DESCRIPTION: ${{ fromJson(steps.get_pr_data.outputs.result).body }}
         COMMIT_DETAILS: ${{ inputs.commit-details }}
-        JIRA_SUMMARY: ${{ env.jira_summary }}
-        JIRA_DESCRIPTION: ${{ env.jira_description }}
+        # JIRA_SUMMARY: ${{ env.jira_summary }}
+        # JIRA_DESCRIPTION: ${{ env.jira_description }}
       run: |
         COMMIT_DETAILS=$(echo "${COMMIT_DETAILS}" | sed 's/\\:/:/g')
-        RELEASE_NOTES="✅ New *${{ github.event.repository.name }}* Release [${{ inputs.version }}](${RELEASE_URL}) $(date)\n${RELEASE_NOTES}\nCommit Details:\n${COMMIT_DETAILS}\nPR Description:\n${PR_DESCRIPTION}\nTicket Details:\n${JIRA_SUMMARY}\n${JIRA_DESCRIPTION}"
+        RELEASE_NOTES="✅ New *${{ github.event.repository.name }}* Release [${{ inputs.version }}](${RELEASE_URL}) $(date)\n${RELEASE_NOTES}\nCommit Details:\n${COMMIT_DETAILS}\nPR Description:\n${PR_DESCRIPTION}"
         RELEASE_NOTES=$(echo -e "${RELEASE_NOTES}" | sed 's/## //g' | sed -r 's/<[^>]*>//g' | sed -r 's/\[([^]]+)\]\(([^)]+)\)/[\1|\2]/g' | sed -r 's/@([^ ]+)/[@\1|https:\/\/github.com\/\1]/g' | sed 's/\\n/<br\/>/g')
 
         payload=$(jq -n \
